name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Ubuntu 20.04, 22.04, 24.04 and the latest Python version
        python-version: ["3.8", "3.10", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: Build package
        run: |
          pip install .
      - name: Test with pytest
        run: pytest
        env:
          PYTHONPATH: .
